name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install texlive-latex-extra texlive-fonts-extra
    - run: make
    - uses: actions/upload-artifact@v3
      with:
        name: cv
        path: cv.pdf
        retention-days: 5
